### ISSUE TITLE
Consider switching to electron-boilerplate to leverage build / test processes

### ISSUE THREAD

**Issue by rpocklin** [ReactivePixels/slinky#12]
Take a look, https://github.com/szwacz/electron-boilerplate it uses rollup, and does proper unit testing / e2e testing with spectron with all the **es6** bits (using *rollup*).  I got mocha running with es6 but when it runs via spectron it doesn't understand the `import` and es6 code inside the application under test.  Only other way to do it would be to transpile all the code into a folder and test that version but it's a bit overly-complicated.

**Comment by rodleviton** [comment]
I have looked at this but it did seem a bit too complex to get started with. Happy to make the switch but would like to weigh up pros and cons before.

**Comment by rpocklin** [comment]
Cool - i've taken the time to produce a branch of this on `using-electron-boilerplater` and created an `appveyor` build (`travis-ci` doesn't show it for me to enable it yet :(

**PROS**
- Built-in support for mocha (unit) / mocha-electron (e2e)
- battle-tested builds and packaging
- uses rollup with gulp (was going to use this anyway?) - very fast
- code coverage
- installer packaging
- specific resources directory (a nice touch)

**CONS**
- uses less (I swapped to use stylus, works fine)
- more dependencies

**Comment by rodleviton** [comment]
@rpocklin awesome work. I will clone and check it out. If it all works (sure it will) we can discuss merging this straight into the master branch.
