### ISSUE TITLE
App Downloads Broken

### ISSUE THREAD

**Issue by chadspencer** [ReactivePixels/slinky#28]
It appears that the download links for the apps on the website at https://reactivepixels.github.io/get-slinky/ are broken. Is there another way I can install the app? I'm on a mac but all downloads appear broken.

**Comment by rodleviton** [comment]
@chadspencer apologies for not responding sooner. We have just rebuilt the package and a version is now available for mac. Please try again and let us know how you go.

https://reactivepixels.github.io/get-slinky/

Cheers
