### ISSUE TITLE
Investigate best way of building binaries for Mac / Windows / Linux

### ISSUE THREAD

**Issue by rpocklin** [ReactivePixels/slinky#3]
Ideal would be via travis or at least automated.

See https://github.com/travis-ci/travis-ci/issues/2104

**Comment by rpocklin** [comment]
Use docker? https://docs.travis-ci.com/user/docker/
https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

**Comment by rpocklin** [comment]
Travis looks good for Linux / Mac.  Need to look at appveyor for windows.

**Comment by rpocklin** [comment]
Need big icon for MAC (and for installer) possibly background if you want

**Comment by rpocklin** [comment]
Appveyer config successful.

**Comment by rodleviton** [comment]
Working for OSX. Split into seperate issues for remaining platforms.
